### ISSUE TITLE
Adding starter modules and files

### ISSUE THREAD

**Issue by nikhilmufc7** [ghostwriternr/dashboard#1]
Hi, I wanted to work on this as part of kwoc, is there a starter code to it if not I would like to start working on it from scratch

**Comment by ghostwriternr** [comment]
Hey @nikhilmufc7!
Our starter code for this repository would be Facebook's official [create-react-app](https://github.com/facebookincubator/create-react-app). We shall be writing our components on top of this boilerplate code.

**Comment by nikhilmufc7** [comment]
Awesome! looking forward to work on it

**Comment by nileshgulia1** [comment]
hello @ghostwriternr  can i work along with @nikhilmufc7  for initialising the app?

**Comment by ghostwriternr** [comment]
I have added the started code to the repo (81b2986).
As a general rule, feel free to go ahead, make the required changes yourself and open a PR. You don't need my permission to work on this project (or any open source project).
