### ISSUE TITLE
Add redux bindings to the project

### ISSUE THREAD

**Issue by ghostwriternr** [ghostwriternr/dashboard#2]
Use redux to manage application state. The official documentation has great tutorials and examples to do so: https://redux.js.org/docs/introduction/Ecosystem.html

It is okay to treat this issue as low-priority and work on the project without redux. This can be integrated eventually.

**Comment by vinitraj10** [comment]
I would like to work on this issue, can i use webpack instead of react-scripts??

**Comment by ghostwriternr** [comment]
Is there a strong reason to do so? The current setup is definitely
sufficient to add redux.

**Comment by ghostwriternr** [comment]
Completed by PR #8.
