### ISSUE TITLE
Create the base component

### ISSUE THREAD

**Issue by ghostwriternr** [ghostwriternr/dashboard#3]
Create the basic component that will act as a container for the entire dashboard. Use the below link as inspiration: https://www.uplabs.com/posts/stripe-dashboard-redesign

Specifically, this container would only contain the sidebar. To start with, create 4 placeholder entries in the sidebar. Create corresponding placeholder containers as well, with container id (ie. simply 1-4).

**Comment by twishasaraiya** [comment]
I would like to take up this issue. Can you tell me the name of four entries??

**Comment by ghostwriternr** [comment]
You could use any 4 placeholder entries. But now that you've asked, use the
following:
- MFQP
- Naarad
- MCMP
- GYFT

These are corresponding to the respective projects under the Metakgp GitHub
org.
