### ISSUE TITLE
Add basic routing

### ISSUE THREAD

**Issue by ghostwriternr** [ghostwriternr/dashboard#4]
The dashboard should by default go to the home container (say the one with container id 1). Upon clicking on one of the sidebar entries, the dashboard should navigate to /{container-id}. For example, if the dashboard is running at http://localhost:8080/, clicking on container 3 in the sidebar should route to http://localhost:8080/3.

**Comment by twishasaraiya** [comment]
I would like to work on routing as well with the sidebar.
