### ISSUE TITLE
Add user login / signup pages.

### ISSUE THREAD

**Issue by ghostwriternr** [ghostwriternr/dashboard#5]
1. Create a component (or two) for handling login and signup. No fancy css needed for the time being.
2. Create a floating (fixed) component in the top right corner of the dashboard (like here: https://www.uplabs.com/posts/stripe-dashboard-redesign). Just one button (doesn't even need an icon. Just something that reads 'user'). Clicking on this button should have a dropdown with 2 entries:
- Profile
- Sign in

**Comment by ghostwriternr** [comment]
The sign-up page must support the following:
1. Have an 'ERP verification' section with 3 fields similar to https://erp.iitkgp.ernet.in/
- Roll number
- Password
- Security question
This should be followed by a 'Verify' button.
2. Have a 'User information' section to collect the following:
i. Name
ii. Email id
iii. Password (for the dashboard)
iv. Confirm password
Followed by a sign-up button.

The sign-in page would simply ask for 2 fields:
i. Roll number
ii. Password

**Comment by silvergame** [comment]
i would like to take this issue ,......can i ?

**Comment by ghostwriternr** [comment]
Sure. You don't need to ask my permission.

**Comment by silvergame** [comment]
@ghostwriternr i implemented some of the requirements..where should i send the code so that u can review if I'm doing right?
p.s : it is just the basic layout....fancy css is yet to be added...I'm new to this ..

**Comment by silvergame** [comment]
hi....I'm stuck at an error ...can u look into it ?? @ghostwriternr

**Comment by twishasaraiya** [comment]
What error are u getting ?? I would like to help

**Comment by silvergame** [comment]
I'm not able to link two components (.js files) ...the error says
"A <Router> may have only one child element"

**Comment by twishasaraiya** [comment]
The description was not quite clear.I am assuming you have two js files each having one component and you want to link them?? Have you put import and export lines

import FirstComponent from '<filename>.js'
class SecondComponent extends React.Component{...}
export default SecondComponent

You can see as I have done [here](https://github.com/ghostwriternr/dashboard/blob/master/src/App.js)

**Comment by ghostwriternr** [comment]
Closing since no longer relevant.
